version: '3.4'

volumes:
  kong_data: {}
  users_data: {}

networks:
  kong-net:

services:
  front-end:
    image: front-end
    build: 
        context: ./angular
        dockerfile: ./Dockerfile
    ports:
      - 4200:80
    networks:
      - kong-net   
    depends_on:
      - users
      - autentificacion

  autentificacion:
    image: autentificacion
    build:
      context: ./autenticacionUsers
      dockerfile: ./Dockerfile
    ports:
      - 8081:8081
    networks:
      - kong-net
    environment:
        SECRET_KEY: abcdefg      
    depends_on:
      - users

  users:
    image: users
    build:
      context: ./rest/users
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    networks:
      - kong-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://Users-database:3306/TiendaVinos?createDatabaseIfNotExist=true
    depends_on:
      - Users-database

  Users-database:
    image: mysql
    hostname: Users-database
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    ports:
      - "3307:3306"
    networks:
      - kong-net
    volumes:
      - users_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1312
      MYSQL_USER: usuario
      MYSQL_PASSWORD: 13121
      MYSQL_DATABASE: Users
      MYSQL_ROOT_HOST: '%'
